services:
  - name: fastapi-app
    type: web
    runtime: python
    region: singapore
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python ./src/app/main.py